default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v9.20.0
  hooks: [{ id: commitlint, stages: [commit-msg], additional_dependencies: ["@commitlint/config-conventional"] }]
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    exclude: '.github/ISSUE_TEMPLATE/.*\.md$'
    additional_dependencies:
    - mdformat-black
    - mdformat-config
    - mdformat-gfm-alerts
    - mdformat-tables
    - mdformat-toc
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
    exclude: '.github/ISSUE_TEMPLATE/.*\.md$'
  - id: forbid-submodules
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [--autofix]
  - id: sort-simple-yaml
    files: .pre-commit-config.yaml
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: hclfmt
    name: hclfmt
    language: docker_image
    entry: alpine/terragrunt:1.10.3 terragrunt hclfmt
    types: ["hcl"]
  - id: commitlint-ci
    name: commitlint-ci
    stages: [manual]
    always_run: true
    language: node
    additional_dependencies: ["@commitlint/config-conventional"]
    entry: bash
    args: ["-c", "npx commitlint --from $PRE_COMMIT_FROM_COMMIT --to $PRE_COMMIT_TO_COMMIT"]
    pass_filenames: false
