site_name: NEW_PROJECT
site_url: https://NEW_ORG.github.io/NEW_PROJECT
repo_url: https://github.com/NEW_ORG/NEW_PROJECT
extra:
  version:
    provider: mike
    alias: true
    default:
      - main
extra_css:
  - stylesheets/extra.css
plugins:
  - mike
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: sphinx
            docstring_section_style: list
            relative_crossrefs: true
            scoped_crossrefs: true
            signature_crossrefs: true
            unwrap_annotated: true
            filters: [""]
            inherited_members: true
            summary: true
            heading_level: 2
            parameter_headings: true
            type_parameter_headings: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            line_length: 88
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            show_signature_type_parameters: true
            backlinks: tree
            show_bases: false
            show_inheritance_diagram: true
  - search
theme:
  favicon: assets/logo.svg
  features:
    - content.code.copy
    - search.highlight
    - search.share
    - versioning
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    scheme: default
