#!/bin/bash
set -ex

export DEVCONTAINER_IMAGE=NEW_PROJECT-devcontainer
export DEVCONTAINER_REGISTRY=ghcr.io/NEW_ORG
export DEVCONTAINER_DEFINITION_TYPE=bake
export DEVCONTAINER_INITIALIZE_PID=$PPID
devcontainer_definition_files_arr=(
  devcontainer-bake.hcl
  docker-client/devcontainer-bake.hcl
  zsh/devcontainer-bake.hcl
  tmux/devcontainer-bake.hcl
  useradd/devcontainer-bake.hcl
  pre-commit/devcontainer-bake.hcl
  cwd://.devcontainer/devcontainer-bake.hcl
)
DEVCONTAINER_DEFINITION_FILES="${devcontainer_definition_files_arr[*]}"
export DEVCONTAINER_DEFINITION_FILES
export DEVCONTAINER_CACHE_BUILD_IMAGE=ghcr.io/rcwbr/devcontainer-cache-build:0.9.2
export DEVCONTAINER_BUILD_ADDITIONAL_ARGS="remote_definition=https://github.com/rcwbr/dockerfile-partials.git#0.12.1"
curl https://raw.githubusercontent.com/rcwbr/devcontainer-cache-build/0.9.2/devcontainer-cache-build-initialize | bash
