name: Push workflow

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  devcontainer-cache-build:
    uses: rcwbr/devcontainer-cache-build/.github/workflows/devcontainer-cache-build.yaml@0.9.2
    permissions:
      packages: write

  release-it-workflow:
    uses: rcwbr/release-it-gh-workflow/.github/workflows/release-it-workflow.yaml@0.5.2
    with:
      app-id: 4269124
      app-environment: Repo release
      release-it-config: .release-it.json
      release-it-image: ghcr.io/rcwbr/release-it-docker-file-bumper:0.8.1
    secrets:
      app-secret: ${{ secrets.RELEASE_IT_GITHUB_APP_KEY }}

  pre-commit:
    if: github.event_name == 'pull_request'
    uses: rcwbr/dockerfile-partials/.github/workflows/pre-commit.yaml@0.4.0
    needs: devcontainer-cache-build
    with:
      pre-commit-image: ${{ fromJSON(needs.devcontainer-cache-build.outputs.devcontainer-cache-image-all_configs).target.pre-commit.args.DEVCONTAINER_PRE_COMMIT_IMAGE }}

  pages:
    # Release pages on tags and main branch
    if: github.event_name != 'pull_request'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: devcontainer-cache-build
    container:
      image: ${{ needs.devcontainer-cache-build.outputs.devcontainer-cache-image-ref }}
      options: --user root
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          token: ${{ github.token }}
